# Generated by Django 4.1.1 on 2022-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.TextField(),
        ),
    ]
